image: Visual Studio 2017

version: 2.0.{build}

environment:
  COVERALLS_REPO_TOKEN:
    secure: w1QgTKjQb/SRT5RvjLDGRniq5S6HV+otG5MywPqt6J3DwZYcddT+/H4SA/YZx/8y

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props;**\*.fsproj;**\*.xml'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

configuration: Release

build:
  parallel: true  
  project: Mongo.Migration.sln
  publish_wap: true               
  publish_wap_xcopy: true         
  publish_azure: true             
  publish_nuget: true             
  publish_nuget_symbols: true     
  include_nuget_references: true
  verbosity: quiet
  
cache:
  - packages -> **\packages.config

before_build:
  - nuget restore

after_test: 
   - cmd: .\post_build.cmd

artifacts:
  - path: Mongo.Migration\bin\Release\net45\Mongo.Migration.dll
    name: Mongo.Migration.dll
  - path: Mongo.Migration\bin\Release\net47\Mongo.Migration.dll
    name: Mongo.Migration.dll
  - path: Mongo.Migration\bin\Release\netstandard2.0\Mongo.Migration.dll
    name: Mongo.Migration.dll
  - path: '**\Mongo.Migration.*.nupkg'

#uncomment to publish to NuGet
#deploy:
#  provider: NuGet
#  api_key:
#    secure: JdTxya5xoPc0b9VqvtkITcfHkvEVrm9GYFRKdv/RNSwwzfnHQYRyBpcexoh9GmAh
#  artifact: /.*\.nupkg/