parameters:
  - name: acrRepoURI
    type: string
    default: 'acr0opp0dev0root0sw.azurecr.io'
  - name: arrayExecs
    type: object
    default:
      - none
  - name: arrayPackages
    type: object
    default:
      - Mongo.Migration
  - name: arrayTests
    type: object
    default:
      - none
  - name: dockerfilePath
    type: string
    default: "none"
  - name: dotNetSdkVersion
    type: string
    default: '6.x'
  - name: gitRepoName
    type: string
    default: "Mongo.Migration"

variables:
  - group: DatadogCI
  - group: github-credentials

pr: none
trigger:
  branches:
    include:
      - 'main'
      - 'master'

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: tools
      type: git
      name: OfficeProtect/tools
      ref: main
    - repository: kube-services
      type: github
      endpoint: op-github-svc
      name: sherweb/kube-services
      ref: dev

stages:
  - stage: CI_CD
    displayName: DotNet Continuous Integration & Deployment
    jobs:
      - template: azdoTemplates/workflows/ci-dotnet.yaml@tools
        parameters:
          acrRepoURI: "${{ parameters.acrRepoURI }}"
          arrayExecs: ${{ parameters.arrayExecs }}
          arrayPackages: ${{ parameters.arrayPackages }}
          arrayTests: ${{ parameters.arrayTests }}
          dockerfilePath: "${{ parameters.dockerfilePath }}"
          dotNetSdkVersion: "${{ parameters.dotNetSdkVersion }}"
          projectPath: "$(System.DefaultWorkingDirectory)/${{ parameters.gitRepoName }}"
      - template: azdoTemplates/workflows/cd-docker.yaml@tools
        parameters:
          env: "dev"
          imageNames: ${{ parameters.arrayExecs }}
